name: thyago-cicd

on: 
  push:
    branches:
      - main

env:
  GO_VERSION: '1.21.x'
  BUILD_DIR: 'build'

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GO ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Display GO version
        run: go version
